server:
  port: 8085
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    name: datasource
    url: jdbc:mysql://47.105.177.123:3306/blogvillage?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Xz13125168081@
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100
      max-request-size: 1024


mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.bear.blogvillage.*.po  # 注意：对应实体类的路径
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1


